ralphbean/bugwarrior

bugwarrior/__init__.py
bugwarrior/command.py
bugwarrior/db.py
bugwarrior/docs/using.rst
setup.py

Currently these are printed to the console during the sync operation, but they're prefixed with logging metadata and are likely to be missed or misused.
This adds a single command that can be ran at any time to generate the current list of active UDAs

Add uda export command

---

bugwarrior/command.py
bugwarrior/config.py
bugwarrior/db.py
bugwarrior/docs/common_configuration.rst
bugwarrior/services/__init__.py
tests/base.py

Flavors allow bugwarrior to be used to populate multiple taskrc lists.
For example, one might have a task list for work and personal use
separately.
---
Fixes #189.

config: add --flavor option

---

bugwarrior/docs/services/gitlab.rst
bugwarrior/services/gitlab.py
tests/test_gitlab.py

It isn't used for anything. Instead, gitlab's queries return all
repositories the user has access to.
---
Turns out it isn't used for anything in the code other than as a suffix to the `gitlab://` keyring URL. Also, the API doesn't support querying based on it anyways.

gitlab: remove 'username' configuration

---

bugwarrior/services/__init__.py
bugwarrior/utils.py
tests/test_utils.py

This should let us expose odd ImportErrors with dependencies in a more
natural way to users (and make the dependencies of the services somewhat
more obvious -- those deps are documented now, but this should help
too).
More informative tracebacks here should fix #132.

Defer importing services until they are needed.

---

bugwarrior/notifications.py

There were a bug when using notification if task has got accentuated caracters:
```
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/home/pferlet/.local/lib/python2.7/site-packages/bugwarrior/command.py", line 62, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/home/pferlet/.local/lib/python2.7/site-packages/bugwarrior/db.py", line 382, in synchronize
TRACE     send_notification(issue, 'Created', conf)
TRACE   File "/home/pferlet/.local/lib/python2.7/site-packages/bugwarrior/notifications.py", line 121, in send_notification
TRACE     message += metadata
TRACE UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 50: ordinal not in range(128)
```
This commit fixes the problem

Fixup notification error with bad encoding

---

bugwarrior/docs/services/jira.rst
bugwarrior/services/jira.py

This will almost certainly be equivalent to the original query for most users; I just happen to have switched recently to a company that used non-standard ticket status names, and knew enough about the JIRA API to know that the proper column to check is `resolution`.
Let me know if you have any questions, sir!

Alter default JIRA query to handle situations in which instances do not use the column names we are expecting.

---

bugwarrior/docs/services/gitlab.rst
bugwarrior/services/gitlab.py

Gitlab *does* paginate, but our instance hadn't had enough traffic for me to notice it until recently. Also adds some more data and fixes a doc typo. Important commit at the base of the branch in case they are wanted separately.

Gitlab pagination

---

bugwarrior/docs/services/phabricator.rst
bugwarrior/services/__init__.py
bugwarrior/services/phab.py

WIP.
The first patch fixes the issue of the python module for phabricator service being called phab, and not phabricator.
The second introduces options to filter out the phabricator tasks and diffs according to the project and the user. (the phabricator service is not really useful now when you have a phabricator setup with many users and projects)
If there is the interest in merging this to mainline, I'll write the documentation for the new options.

Phabricator service: Adding option to filter on users and projects

---

setup.py

Enable the canonical setuptools test command to invoke the tests via nose as per documentation:
http://nose.readthedocs.org/en/latest/setuptools_integration.html

Enable setuptools test command

---

bugwarrior/docs/services/bugzilla.rst
bugwarrior/services/bz.py

In newer BZ installations, the NEEDINFO status has been replaced with the `needinfo` flag. This commit adds a config option to also query for bugs where you are a requestee on the needinfo flag.
This also adds a "bugzillaneedinfo" UDA so queries like `task bugzillaneedinfo.any: list` return all your needinfo bugs.

Support needinfo bugs where you are not CC/assignee/reporter

---

bugwarrior/services/gitlab.py

The Gitlab service seems to always import all issues, including closed ones. This PR changes that behaviour.

Only import active Gitlab issues and merge requests

---

bugwarrior/docs/common_configuration.rst
bugwarrior/docs/configuration.rst
bugwarrior/services/__init__.py

This patch adds a general config option `annotation_comments` that defaults to True (current behavior) and lets users turn off annotations for issue comments. This is super handy if you're on large github issue threads.

Make comment annotation configurable

---

bugwarrior/db.py
bugwarrior/docs/configuration.rst

We get weird bug reports for it all the time.
We've had the new code in place long enough that many users have
hopefully migrated to the new UDA scheme.  This should turn it off for
new users by default, hopefully providing a better experience.

Turn legacy_matching off by default.

---

bugwarrior/docs/configuration.rst

New users get an error when the section header is present, but no
options.  Let's set them up for success.

Comment out this section header.

---

bugwarrior/docs/services/pagure.rst
bugwarrior/services/__init__.py
bugwarrior/services/pagure.py

Support for pagure.io.

---

bugwarrior/docs/services/github.rst

Access tokens now have their own section in github settings

Update instructions to get a github token

---

bugwarrior/services/gitlab.py

To prevent issue updates on every bugwarrior-pull.  See #259.

Ignore microseconds for gitlab

---

setup.py

I had to install pypandoc and pyac for all the tests to pass.  Note that
pypandoc probably requires pandoc to be installed as well.

Add missing test dependencies

---

bugwarrior/db.py

- If the section doesn't exist, `_bool_option` should return the given
default value, not `False`
- The fourth argument of `conf.get()` is not a fallback value but controls
how the value is parsed ([1])
- `"False"` is true-ish, which was causing `legacy_matching` to be true by
default
[1] https://docs.python.org/2/library/configparser.html#ConfigParser.ConfigParser.get
In addition. the `legacy_matching` option behave erratically if the issue description contains pipes (`|`). But since it seems deprecated, I don't know if it's worth fixing.

Fix some subtle option parsing problems:

---

.travis.yml
bugwarrior/docs/common_configuration.rst
bugwarrior/docs/contributing.rst

Simply running `nosetests` wont work because dependencies aren't installed
in the virtualenv. You'd have to manually `pip install` each dependency
like travis currently does.
Nose recommends this as "the easiest way to run tests with nose".
http://nose.readthedocs.org/en/latest/api/commands.html

Minimal CI and documentation fixes.

---

bugwarrior/services/bitbucket.py

This status was recently added and still isn't in the API docs, but the
API does return it.
https://bitbucket.org/site/master/issues/5179/add-a-status-of-closed-to-issues-bb-10249

Bitbucket closed status

---

bugwarrior/services/bitbucket.py
tests/test_bitbucket.py

- Moving most things to the v2 API makes some things cleaner.
- One DRY get_data function that takes an optional api kwarg.
- Still no way to get detailed comment data without making an extra api
call, so let's put that off for now.

bitbucket: More v2 API. Progress on #129.

---

bugwarrior/command.py
bugwarrior/config.py
bugwarrior/db.py
bugwarrior/services/__init__.py
bugwarrior/services/bitbucket.py
bugwarrior/services/bz.py
bugwarrior/services/github.py
bugwarrior/services/gitlab.py
bugwarrior/services/jira.py
bugwarrior/services/mplan.py
bugwarrior/services/teamlab.py
bugwarrior/services/trac.py
bugwarrior/services/versionone.py
tests/test_bitbucket.py
tests/test_gitlab.py

* Fix a bug that prevented using an `@oracle:` token in gitlab
* improve error reporting in case a `@oracle:eval:` commands fails
* fix a bug that made bugwarrior hang when the oracle failed

Password oracle improvements

---

bugwarrior/docs/services/phabricator.rst
bugwarrior/services/phab.py

If self.shown_user_phids or self.shown_project_phids is set, restrict API calls to user_phids or project_phids to avoid time out with Phabricator installations with huge userbase.

Avoid time out with Phabricator installations with huge userbase

---

bugwarrior/services/bitbucket.py

I'm getting `state` rather than `status` for issues, though `status` is
the documented name <https://confluence.atlassian.com/bitbucket/issues-resource-296095191.html>.

Fix bitbucket undocumented API change.

---

bugwarrior/command.py
bugwarrior/config.py
bugwarrior/data.py
bugwarrior/docs/services/bitbucket.rst
bugwarrior/services/bitbucket.py

- Implement OAuth2. Thanks to @ibuchanan for helping me navigate
bitbucket's idiosyncratic implementation.
- Add a bugwarrior.data file to the ~/.task directory, per [taskwarrior's
third-party guidelines](https://taskwarrior.org/docs/3rd-party.html#guidelines).

Bitbucket OAuth. Resolve #201.

---

bugwarrior/command.py
bugwarrior/services/__init__.py

The 'development' configuration option is not currently documented. Rather than document
it, I suggest using a flag because it's more convenient (doesn't require
constantly editing a file) and self-documenting.

Replace development config with --debug flag.

---

bugwarrior/services/activecollab2.py
bugwarrior/services/teamlab.py

Note: I do not have any way to test this out on these services.

Replace remaining urrlib2 usage with requests.

---

bugwarrior/services/github.py

Prior to this change, comments on Github issues were fetched
(generating their own API request) whether or not they were saved in
taskwarrior per the `annotation_comments` config option. This change
only fetches them if `annotation_comments` is True, saving requests &
time.

Fetch github comments only when they will be used

---

bugwarrior/services/__init__.py

In 81e8d74d0, we accidentally changed the config value from
``only_if_assigned`` to ``$SERVICE.only_if_assigned``.  That's okay by me,
just because it makes things consistent.  But, it breaks people's existing
configs (it broke mine).
This change adds some warnings which will halt bugwarrior and prompt you to
update your config.

Complain when users specify old config values.

---

bugwarrior/services/__init__.py
bugwarrior/services/activecollab2.py
bugwarrior/services/bitbucket.py
bugwarrior/services/gitlab.py
bugwarrior/services/redmine.py
bugwarrior/services/taiga.py
bugwarrior/services/teamlab.py

The only difference is that errors will include the full url (i.e,
inluding params), which is probably a good thing anyway.
This also fixes the regression I introduced into taiga in which I forgot
to include the url.

Simplify SerivceClient.json_response interface.

---

bugwarrior/docs/common_configuration.rst
bugwarrior/docs/conf.py
bugwarrior/docs/contributing.rst

* Fix typo in option name 'inline_links' in docs
* Enable syntax coloring for configuration examples

Documentation improvements

---

bugwarrior/README.rst

See <https://blog.readthedocs.com/securing-subdomains/>:
> Projects will automatically be redirected, and this redirect will remain in place for the foreseeable future. Still, you should plan on updating links to your documentation after the new domain goes live.

Update docs link to readthedocs.io.

---

bugwarrior/docs/services/github.rst
bugwarrior/services/github.py

This is a new option to fix #314. I set the default to be backward compatible so it shouldn't change bugwarrior's behavior for existing users.

Github: add an option to skip user issues

---

bugwarrior/services/github.py
tests/test_github.py

It seems that the distinction was not properly documented for some time,
but it now is. `/user/repos` includes all repos the authorized user has
access to, but `/users/:username/repos` only includes public repos.
http://stackoverflow.com/questions/21907278/github-api-using-repo-scope-but-still-cant-see-private-repos
**Note**: This doesn't break anything for me but I'm not super familiar with the configuration options and am not sure if this might accidentally change their behavior.

Include github private repos (take 2). Fix #282.

---

bugwarrior/services/__init__.py

The `die()` function was used in `IssueService.validate_config()`, but it was never imported.
This bug was found using [pyflakes](https://github.com/pyflakes/pyflakes).

Add missing import

---

bugwarrior/services/github.py
bugwarrior/services/pagure.py

This should make things marginally faster.  When not using sessions, we
have to keep initiating new TCP connections over and over again.  Wasted
overhead.

Use requests "sessions".

---

bugwarrior/command.py
bugwarrior/config.py
bugwarrior/db.py
bugwarrior/services/__init__.py
bugwarrior/services/activecollab.py
bugwarrior/services/activecollab2.py
bugwarrior/services/bitbucket.py
bugwarrior/services/bz.py
bugwarrior/services/github.py
bugwarrior/services/gitlab.py
bugwarrior/services/mplan.py
bugwarrior/services/pagure.py
bugwarrior/services/phab.py
bugwarrior/services/redmine.py
bugwarrior/services/teamlab.py
bugwarrior/services/trac.py
setup.py

I used it on a whim when I first started writing bugwarrior, but it has
proved to be annoying.  It has problems interpolating strings when we
don't want it to and it has all kinds of weird encoding handling that
keeps raising new bugs.
The stdlib logging is sufficient.

Kill twiggy.

---

tests/test_trac.py

The tests were not expecting a traccomponent UDA, and this commit fixes that.

Update Trac tests to include component UDA

---

bugwarrior/services/github.py

There are some default headers attached to requests sessions:
```python
>>> import requests
>>> s = requests.session()
>>> print(s.headers)
{
'Connection': 'keep-alive',
'Accept-Encoding': 'gzip, deflate',
'Accept': '*/*',
'User-Agent': 'python-requests/2.10.0',
}
```
In #332 we accidentally started overwriting all of those defaults.
This change brings them back into play and should fix #345.

Modify headers instead of overwriting.

---

bugwarrior/docs/getting.rst

In ZSH running `pip install bugwarrior[jira] doesn't work as the shell will try to interpret bugwarrior[jira] as a command. Therefore I've added a hint on how to install the Jira plugin on ZSH which requires adding quotation marks around the installation target.

Make Jira installation example in docs ZSH compatible

---

bugwarrior/command.py

This should protect it from cold-blooded killers like @ralphbean.
(See #333.)

Add help text to bugwarrior-pull's --debug flag.

---

bugwarrior/services/bitbucket.py

This silences all the warnings from taskw that a number is being coerced
into a string.
I'm not sure what the ramifications of this might be. Looking at the json files, this doesn't appear to have caused an automatic migration or duplication among existing tasks. Any thoughts on how to proceed would be appreciated.

Make bitbucketid numeric.

---

.travis.yml
bugwarrior/README.rst
bugwarrior/docs/services/bts.rst
bugwarrior/services/bts.py
setup.py
tests/test_bts.py

This pull request adds a service ```bts``` for the Debian Bug Tracking System (BTS) that is used to track bugs on packages distributed as part of the Debian Operating System.
This pull request closes #327.

Debian BTS support

---

bugwarrior/db.py

Because of the import
from __future__ import unicode_literals
We can pass all the arguments as unicode and let the logging library
take care of the encoding.

Fix some problems with unicode

---

bugwarrior/services/github.py
tests/test_github.py

Note that the milestone id that was used before is the intertal github
id for the row, not the sequencial milestone number included in the url.
As such I didn't keep it at all as I assumed that it was fairly useless
for everyone.
The milestone number may eventually be useful but I guess we should
wait until someone asks for it explicitely before adding it to avoid
some sort of "UDA creap".
Fix issue #365

Use milestone title instead of id for githubmilestone

---

bugwarrior/docs/services/gitlab.rst
bugwarrior/services/gitlab.py
tests/test_gitlab.py

The documentation said that to include/exclude a repository you should
simply write the project name, like `bar` but actually, the service
expects a namespace in the repository name, e.g. `foo/bar`.
This commit does two things:
* If the user writes a repository name without the namespace,
automatically adds the value of `gitlab.login` as the namespace.
* Update the gitlab documentation accordingly

Fix gitlab include/exclude repos

---

bugwarrior/command.py

Catch IOError when loading config, useful message

---

bugwarrior/config.py
bugwarrior/docs/common_configuration.rst
setup.py
tests/test_config.py

* If `$BUGWARRIORRC` is set, then bugwarrior will try to read its
configuration file from its content
* Extract the code that guess the path to the configuration file in its
own function.
* Add some unit tests
I got a bit tired of editing my own `.bugwarriorrc` to test bugwarrior. This is inspired by the similar variable `TASKRC` used by taskwarrior.

Add support for environment variable $BUGWARRIORRC

---

bugwarrior/services/bts.py

Just some extra config validation.

bts: Reject configuration if UDD options specified but UDD not used

---

bugwarrior/docs/services/jira.rst
bugwarrior/services/jira.py

I'd like to import more jira attributes (like use the end date of the sprint as
the due date for active issues in the sprint), but that's a bit more
complicated and can wait until later.

Import JIRA sprint names as labels.

---

bugwarrior/services/github.py

Previously, setting `involved_issues = True` would pull in PRs that were in any
state, including merged PRs. This patch amends the involved issues query to
only search for open PRs.

Only query for open github PRs (#377)

---

bugwarrior/notifications.py

Problem came from mixing unicode and non-unicode strings in %-formatting.  Fixed by using only unicode, which should make the code more python 3 compatible as well.
This also supress a warning when using gobject notifications

Fix unicode issues in notifications

---

.travis.yml
bugwarrior/command.py
bugwarrior/config.py
bugwarrior/data.py
bugwarrior/db.py
bugwarrior/docs/using.rst
bugwarrior/services/__init__.py
bugwarrior/services/bitbucket.py
setup.py
tests/base.py
tests/test_activecollab.py
tests/test_activecollab2.py
tests/test_bitbucket.py
tests/test_bts.py
tests/test_bugzilla.py
tests/test_config.py
tests/test_data.py
tests/test_gerrit.py
tests/test_github.py
tests/test_gitlab.py
tests/test_jira.py
tests/test_megaplan.py
tests/test_redmine.py
tests/test_taiga.py
tests/test_teamlab.py
tests/test_templates.py
tests/test_trac.py
tests/test_trello.py

Since we support multiple config flavors, we need to ask taskwarrior
(given the current flavor's taskrc) what the data location is.
Thanks to @mathstuf for taking the lead on this. I copied some of the
code from #363 and tried for a cleaner implementation of his idea.

Get data location from taskwarrior.

---

bugwarrior/docs/services/redmine.rst
bugwarrior/services/redmine.py

This is quick and dirty patch to increase current limitation from 25 records
returned to 100 (hard coded maximum). Fore more, we'd need to implement
pagination. Since I have less then 100 bugs assigned, I am not interested in
that for the moment. But who knows :-)

redmine: import first 100 issues instead 25

---

bugwarrior/services/gitlab.py

---
When fetching all TODO items, the branch did not match the type used when filtering todo items.

gitlab: match types when including all todo items

---

bugwarrior/docs/services/gitlab.rst
bugwarrior/services/__init__.py
bugwarrior/services/gitlab.py

This adds a new option to the gitlab service for `only_if_author` which works
similarly to `only_if_assigned`. It is useful for making sure MRs and issues
that you put in stay on your radar until they are merged or closed out.
this is a workaround that fixes #402 , you can list all of your projects and it mimics the gitlab dashboard, but in TW.

Filter gitlab requests by author

---

bugwarrior/config.py
bugwarrior/data.py
bugwarrior/services/__init__.py
bugwarrior/services/bitbucket.py
tests/base.py
tests/test_config.py
tests/test_data.py
tests/test_github.py

The oracle now returns the password as a unicode string.  The password
is decoded using the UTF-8 coding as this is the python 3 default.

Fix @oracle:eval with Github and python 3

---

bugwarrior/notifications.py

Fixes "UnicodeDecodeError: 'ascii' codec can't decode byte X in position N: ordinal not in range(128)", which occurs if Phabricator task titles contain unicode characters.

Fix gobject notifications with unicode characters

---

bugwarrior/docs/services/jira.rst
bugwarrior/services/jira.py

This will make it possible to authenticate to Jira server using Kerberos by specifying password as magic value `@kerberos`.
Currently released `jira` package does not work with servers that do not support mutual authentication, so this would not work for some people. See related issue https://github.com/pycontribs/jira/issues/274.

Add kerberos authentication to JiraService

---

bugwarrior/services/__init__.py

Before passing an exception out of the service worker, we should remove attributes that could break pickling.
Turns out this is caused by using kerberos: it adds a hook to the request and that causes the break.

Remove unpickleable attributes from exception

---

bugwarrior/services/__init__.py

If the worker fails `bugwarrior-pull` may get stuck:
```
INFO:bugwarrior.services:Working on [jira.redhat]
ERROR:requests_kerberos.kerberos_:handle_other(): Mutual authentication failed
INFO:bugwarrior.services:Done with [jira.redhat] in 1.376839s
Traceback (most recent call last):
File "/usr/bin/bugwarrior-pull", line 9, in <module>
load_entry_point('bugwarrior==1.4.0', 'console_scripts', 'bugwarrior-pull')()
File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python2.7/site-packages/click/core.py", …
```

Make sure e.request is not None before removing hooks

---

bugwarrior/services/gerrit.py
tests/test_gerrit.py

Useful when tracking work in projects that use multiple branches for
development and maintenance, such as Openstack.

gerrit: Track the branch and topic used by each change

---

bugwarrior/docs/services/redmine.rst
bugwarrior/services/redmine.py
tests/test_redmine.py

This PR is for #390. I'm posting this now in case someone wants to carry on, I'm going to be mostly offline for the next few weeks. (If you do work on this please post here so we're not working to cross purposes!)
Still TODO:
- Load comments as annotations
- Support for custom fields
- Pagination support for more than 100 records?
- Fix tests
Everything here is working for me, btw.

Redmine improvements

---

.travis.yml
bugwarrior/services/jira.py
tox.ini

The issue is that they added a new keyword argument to a method that we override.  Our method signature didn't match.
I dropped the details to try and immunize ourself against any future changes.

Test and fix our usage of different python-jira versions.

---

bugwarrior/docs/services/github.rst
bugwarrior/services/github.py
tests/test_github.py

Fixes #423 and then some by allowing arbitrary github queries.
I'm not sure this is the best way to do the tests -- it repeats a lot of boilerplate just to run the service with slightly different parameters.

Implement `github.query` for the github service

---

bugwarrior/config.py
bugwarrior/services/__init__.py
tests/test_config.py
tests/test_service.py

<s>This is alternative proposal to #436.
The advantage to subclassing ConfigParser rather than using
allow_no_value is that we don't have to worry about handling None for
other value types.</s>

Allow unlimited description and annotation lengths. Resolve #441.

---

bugwarrior/command.py
bugwarrior/config.py
bugwarrior/services/__init__.py
bugwarrior/services/activecollab.py
bugwarrior/services/activecollab2.py
bugwarrior/services/bitbucket.py
bugwarrior/services/bts.py
bugwarrior/services/bz.py
bugwarrior/services/gerrit.py
bugwarrior/services/github.py
bugwarrior/services/gitlab.py
bugwarrior/services/jira.py
bugwarrior/services/mplan.py
bugwarrior/services/pagure.py
bugwarrior/services/phab.py
bugwarrior/services/redmine.py
bugwarrior/services/taiga.py
bugwarrior/services/teamlab.py
bugwarrior/services/trac.py
bugwarrior/services/trello.py
bugwarrior/services/versionone.py
bugwarrior/services/youtrack.py
tests/test_config.py
tests/test_github.py
tests/test_gitlab.py
tests/test_trello.py
tests/test_youtrak.py

The `IssueService.config_*` methods are part of a concept that wants to be it's own
object. The functionality of these convenience methods is
duplicated wherever an `IssueService` instance is not available
(validate_config, get_keyring_service, etc.), indicating that they're in
the wrong place.

Service config refactor.

---

bugwarrior/docs/services/bugzilla.rst
bugwarrior/services/bz.py
tests/test_bugzilla.py

python-bugzilla refers to these as [tokens](https://github.com/python-bugzilla/python-bugzilla/commit/e1af7160b3162d423fdfeb04e230067a75e9b584).  It would be nice to be able to create an API key and provide it as
```
[bugzilla_mozilla]
bugzilla.username = dustin@mozilla.com
bugzilla.token = e1af7160b3162d423fdfeb04e230067a75e9b584
```

Support Bugzilla API keys (pending support in python-bugzilla)

---

bugwarrior/docs/common_configuration.rst
bugwarrior/docs/services/trac.rst
bugwarrior/services/__init__.py

Field templates should be loaded with the corresponding service prefix:
```bugzilla.description_template``` is the ```description_template``` for the
Bugzilla service.
At least the documentation (code comments and user docs) needs to
updated before this can be merged. Am I on the right track with this PR?
See: #466

Use service prefix for field templates

---

bugwarrior/services/bz.py
tests/test_bugzilla.py

This allows to use a ```project_template``` with a value of
```{{ bugzillaproduct }}.{{ bugzillacomponent }}``` which is nicely rendered
by taskwarrior as:
```
$ task projects
Project                      Tasks
product                         10
component1                     1
component2                     7
componentN                     2
```
Bugzilla has more fields which might be useful as UDA:
* 5.0: https://bugzilla.readthedocs.io/en/5.0/using/understanding.html
* 4.4: https://www.bugzilla.org/docs/4.4/en/html/bug_page.html

Add product and component as UDA for bugzilla

---

bugwarrior/services/jira.py
tests/test_jira.py

Fix for issue #450 by converting unicode timestamp to offset-aware datetime object.

Issue #450 fix for JIRA entry datetime comparison

---

.travis.yml
bugwarrior/data.py
bugwarrior/docs/configuration.rst
bugwarrior/docs/services/gmail.rst
bugwarrior/services/gmail.py
setup.py
tests/test_data.py
tests/test_gmail.py

Add a service using Google APIs to fetch e-mails as tasks. You
can specify a query using the google search syntex to specify
which e-mails to fetch. Authentication is performed via oauth
and will require the user to set up a production and download
a client_secret file.
The default query is starred threads. No support for pinning and
snoozing yet as I don't use this. I think support for google tasks
could be extended from this easily.

GMail service for bugwarrior

---

bugwarrior/services/gmail.py

If any command line arguments are passed to bugwarrior, gmail will try
to parse them and fail. It's not possible pass arguments to Oauth this
way anyway (because bugwarrior would reject the unrecognised command
line arguments), so we shouldn't try to do it. (I see no reason to pass
flags to OAuth here, if needed we'd have to find another way.)
Should resolve issue #488.

Gmail oauth flow shouldn't attempt to parse the command line.

---

bugwarrior/docs/common_configuration.rst
bugwarrior/docs/configuration.rst
bugwarrior/services/__init__.py

Update documentation for common service configuration options, namely the new requirement of prefixing these options with the service name.
Also add validation for `default_priority` and `add_tags` options (previously only done for `only_if_assigned` and `also_unassigned`).

Common configuration options: update documentation + complete validation

---

bugwarrior/config.py
bugwarrior/services/__init__.py

Hi there fabulous maintainers! You've probably seen me bouncing around issues for a while, so I'm hoping to give something back to the main codebase. To help familiarise myself with the code I'm working on making very small and easy changes where I can spot them.
I'm still a relative python newbie, and this is my first pull-request to bugwarrior, so feedback on style and code is very much appreciated. If I've done things in a particularly odd way it's probably because I didn't know there was a better alternative. :)
I noticed that `services/__init__` had a lot of repeated code for handling defaults and configuration. In this change I've refactored that int a separate method, which reduces our line-count and I hope also reduces our complexity.
If these sorts of code cleaning changes are …

services/__init__: Refactor handling of defaults

---

bugwarrior/config.py
bugwarrior/db.py
bugwarrior/services/__init__.py
bugwarrior/services/bz.py
tests/test_db.py

Code to split config options on commas was duplicated in a number of
places, not all of which remembered to strip leading and trailing
whitespace.
Resolves issue #490.

Use aslist everywhere when parsing list config options.

---

bugwarrior/docs/services/taiga.rst
bugwarrior/services/taiga.py

By default tasks are not included into the taiga pull.
I hacked access to assigned tasks into the taiga service, but probably this should be configurable at some point?
Before I dive deep into making this really clean I wanted to know whether this has a chance of getting merged into the main project.
Cheers
Felix

WIP: Also include tasks for taiga

---

MANIFEST.in

The current (1.5.1) source distribution contains compiled python files/artifacts in the tests/ directory.
This change excludes them globally from source distributions.

Globally exclude __pycache__ and py[co] from sdist

---

bugwarrior/services/gerrit.py

The account information [1] and [2] on gerrit has changed over time. The
change add a fallback way when all optional fields are not set to use
the non-optional fields `_account_id`.
Additionally I use `[author][name]` as default, because `[author][username]` is more a information for authentication systems.
[1]: https://gerrit-documentation.storage.googleapis.com/Documentation/2.9/rest-api-accounts.html#account-info
[2]: https://gerrit-documentation.storage.googleapis.com/Documentation/2.14/rest-api-accounts.html#account-info
Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

add fallback way for annotation on gerrit service

---

bugwarrior/docs/services/gitlab.rst
bugwarrior/services/gitlab.py

This introduces the service options `gitlab.include_regex` and `gitlab.exclude_regex`, which can be used in addition to the existing lists in `gitlab.include_repos` and `gitlab.exclude_repos`.
For my use case: I would like to import all issues of the repos in my own namespace; I feel responsible of those even when I'm not assigned. Also I want the issues that are assigned to me in organization repos (I don't care about the rest, someone else can grab them :P)
So basically I want two different services, one with `gitlab.only_if_assigned` seti to my username, matching only the organization repos, and one without that option matching my own repos. However, the GitLab service (or even the API? I'm not sure) lists all accessible repos, even in organizations. So I would have to maintain an …

gitlab: filter repositories by regex

---

bugwarrior/docs/common_configuration.rst

The last paragraph probably gets overread a lot (like in my case), so make the service-prefixing more clear and put the paragraph to the top so it doesn't get lost under the list.
Mention default values and make the documentation reflect the implementation better, and try to add more clarity.

doc: rework section Common Service Configuration Options

---

bugwarrior/db.py

A KeyError is thrown when I have a field in the static_fields config that is not implemented in a specific service. Rather than have the KeyError get thrown, I figured it makes sense to add a check to confirm whether or not the field even exists in the issue.

Modify drop static field logic to prevent KeyError

---

bugwarrior/services/redmine.py

python is complaining about not enough arguments.
I couldn't test because of retro-incompatibility with my Redmine (3.2.0.stable.15005)
I got NameError: name 'DESCRIPTION' is not defined

TypeError: not enough arguments for format string

---

bugwarrior/docs/configuration.rst

add_tags requires a comma separated list of tags, not a space separated list as currently in the example configuration. This changes the example accordingly.

Use comma instead of space separated list for [service].add_tags in example configuration

---

bugwarrior/services/redmine.py

This allows you to put the API key into @oracle mode so you don't have
to store clear text API keys in your configuration.
This should not have any effect on existing configuration.

Use get_password to evaluate API key

---

bugwarrior/config.py
tests/test_config.py

This change copies our existing environment and then makes changes to it
before calling `task`, rather than creating an empty environment and
populating it.
This is much friendlier to any hooks the user may have set.
Replaces #531.
Closes #533.

Preserve existing environment variables when calling task

---

bugwarrior/services/jira.py
tests/test_jira.py

bugwarrior-pull updates all Jira issues on every run like this:
entry: datetime.datetime(2018, 1, 8, 16, 31, 4, tzinfo=tzutc())
-> datetime.datetime(2018, 1, 8, 17, 31, 4, 855000, tzinfo=tzoffset(None, 3600))
This patch changes timezone of the Jira issue to UTC (as is the default
for taskwarrior) and strips away the microseconds, as they are not
represented in taskwarrior.

Convert Jira time to UTC and strip microseconds (Closes: #450)

---

bugwarrior/docs/services/phabricator.rst
bugwarrior/services/phab.py

Right now behaviour is undefined as the phabricator library uses:
`(defined_hosts.keys())[0]` when the `host` parameter is not passed.
This enables usage of multiple phabricator instances with bugwarrior.

Add phabricator.host option to enable multiple instances

---

bugwarrior/services/phab.py

phabricator could be runned without `Differential` or Review.
```
phabricator.APIError: ERR-CONDUIT-CALL: Method 'differential.query' belongs to application 'Differential', which is not installed.
```
---
A solution is to put this part in a try block

[phabricator] Connect to phabricator without Differential

---

bugwarrior/services/gitlab.py
tests/test_gitlab.py

Also use URL query to exclude tasks other than opened/pending to drastically increase pull speed.
fixes #583

gitlab: migrate to APIv4

---

bugwarrior/services/gitlab.py
tests/test_gitlab.py

I always ran into errors when pulling in gitlab MRs which changed their WIP status. Today I found some time to debug this and it seems to be a type error. The WIP status seems to be either 'False' or 'True' coming from the server, but the UDA is set to numeric. I changed it to string and now my issues drop in without problems. 
As far as I can see, this value is used nowhere else, so this MR shouldn't do any harm.
Oh, btw, I'm using Gitlab 10.8.2. I don't know if they ever changed their API on that, just in case...

gitlab WIP status is True or False. This does not convert to numerics.

---

bugwarrior/docs/services/redmine.rst
bugwarrior/services/redmine.py

Add configuration option `verify_ssl` for redmine service, that allows to ignore verifying the SSL certificate.

Redmine: add verify_ssl configuration option

---

bugwarrior/services/gitlab.py

The title says it all: we don't need to fetch notes if **annotation_comments** is set to **False**.

gitlab: fetch annotations only if necessary

---

bugwarrior/config.py
bugwarrior/db.py
bugwarrior/services/gitlab.py
bugwarrior/services/trello.py
tests/test_bugzilla.py
tests/test_config.py
tests/test_data.py
tests/test_db.py
tests/test_github.py
tests/test_gitlab.py
tests/test_trello.py
tests/test_youtrak.py

Uses the portable configparser name from six to avoid failure on py27.

Fix tests on py27 due to configparser

---

bugwarrior/services/jira.py
tests/test_jira.py

Jira doesn't escape commas in the value field of the sprint string so it's not safe to  just split on all commas.
In my case, I ran into a sprint with a goal that contained a bunch of commas.
Splitting on the `=` character and then using `rsplit` to only grab the last `,` is maybe a bit safer.

Fix jira sprint parsing

---

bugwarrior/config.py
tests/test_config.py

This commit allows the user to define paths for logging that are absolute or relative, or that contain environment variables or the `~` for the user home folder.
Examples:
1. `/var/log/bugwarrior.log`
2. `$HOME/var/log/bugwarrior.log`
3. `~/.local/var/log/bugwarrior.log`
4. `bugwarrior.log`

Handle paths absolutes or with envvars for logging

---

bugwarrior/docs/services/github.rst
bugwarrior/services/github.py

In my workflow I only track issues and not pull requests. Pull requests usually refer to issues that I resolve so tracking both results in duplicate tasks.

Add the ability to exclude Github pull-requests

---

bugwarrior/services/jira.py

The priority.name field returns something more like "1 - Critical". Split the string to get the PRIORITY_MAP key.

jira: split priority.name for lookup

---

bugwarrior/services/github.py

I think this is the desired behavior.  If you have a config with only one
`include_repos` repo set, bugwarrior shouldn't bother querying for and paging
through all the repos of the user.  We can short-circuit that and assume the
repo exists.

GitHub: Only query for user repos if an include_repos list is not specified

---

bugwarrior/db.py
tests/test_db.py

Fixes #601.
This can happen if, for instance, you have two github targets declared which
query in different ways.  They may each find the same issue which (without this
patch) may both be written to taskwarrior as duplicates.  After duplicates are
in place, it is difficult for bugwarrior to figure out which one to apply
annotation updates to.

De-duplicate issues before first write to taskwarrior.
