ralphbean/bugwarrior

bugwarrior/db.py
As discussed in ralphbean/taskw#87.
=> Hack to let task-2.4.x search for url UDAs.

bugwarrior/command.py, bugwarrior/config.py, bugwarrior/docs/common_configuration.rst, bugwarrior/docs/configuration.rst, bugwarrior/docs/using.rst, bugwarrior/services/activecollab2.py, setup.py
Adds support for `XDG_CONFIG_HOME` storage of the configuration file with fallback to the original file.
=> XDG support

bugwarrior/README.rst, bugwarrior/docs/services/github.rst, bugwarrior/docs/services/gitlab.rst, bugwarrior/services/__init__.py, bugwarrior/services/gitlab.py, tests/test_gitlab.py
Tested with an internal version of gitlab. Fixes #188.
---
Needs docs and tests yet.
=> gitlab: add initial gitlab support

bugwarrior/services/gitlab.py
=> gitlab: verify SSL certs

bugwarrior/db.py
=> db: fix missing argument

bugwarrior/docs/services/github.rst, bugwarrior/services/github.py, bugwarrior/services/githubutils.py
=> github: add support for OAuth2 authentication

bugwarrior/docs/services/bitbucket.rst, bugwarrior/services/bitbucket.py
---
Started off as just adding filtering to bitbucket, but I also added pull request logic. It's really sad that all these sites have slightly different APIisms. Bitbucket is, so far, the worst documented out of itself, gitlab, and github :( . Pinging #129 since now there's a mix of v1 and v2 usage here.
=> Bitbucket filter repo

bugwarrior/db.py, bugwarrior/docs/common_configuration.rst
This should fix #171.  @djmitche, can you confirm?
=> Make merging in annotations to the task db optional.

MANIFEST.in
Add tests to MANIFEST.in so that they are included in the sdist on PyPI.
This allows users & packagers downstream to QA using release distributions.
=> Add tests to MANIFEST.in

bugwarrior/docs/services/github.rst, bugwarrior/services/github.py, bugwarrior/services/githubutils.py
---
I've asked GitHub (again) for a real API endpoint for this. Searching is slow.
=> GitHub involved issues

bugwarrior/services/gitlab.py
---
I'm pretty sure this is what I have sitting at work. I'll have to double check.
=> Handle broken gitlab pagination

bugwarrior/services/gitlab.py
Not everyone uses HTTPS for GitLab unfortuently.
Hope this is okay.
=> Include an option to disable HTTPS for GitLab.

bugwarrior/docs/services/gitlab.rst
=> Add gitlab.host to example Gitlab target

bugwarrior/docs/services/gitlab.rst, bugwarrior/services/gitlab.py
=> add verify_ssl option to gitlab service

bugwarrior/docs/services/bitbucket.rst
The implementation seems to be the same as github.
=> bitbucket.login is a required setting

.travis.yml
I don't think the number matters that much and I wouldn't want to make
coverage a hard rule for PR's, but I think keeping an eye on the affect
our changes make would help us move in the right direction.
=> Add Coveralls coverage testing to CI.

bugwarrior/docs/services/redmine.rst, bugwarrior/services/__init__.py, bugwarrior/services/bitbucket.py, bugwarrior/services/redmine.py
Thanks to @rocketnova for the initial implementation. Note that I do not have a redmine instance to test against.
=> Redmine basic auth. Resolve #295.

bugwarrior/README.rst, bugwarrior/docs/services/taiga.rst, bugwarrior/services/__init__.py, bugwarrior/services/taiga.py, setup.py, tests/test_taiga.py
=> A service for pulling issues from a taiga instance.

bugwarrior/services/__init__.py, bugwarrior/services/activecollab2.py, bugwarrior/services/bitbucket.py, bugwarrior/services/gitlab.py, bugwarrior/services/redmine.py, bugwarrior/services/taiga.py, bugwarrior/services/teamlab.py
This seems to be the direction the abstraction is going in and facilitates DRYing up the json response handling.
=> Service Client Base Class

bugwarrior/services/__init__.py
This should not change the logical behavior.
=> Clean up IssueService.include

bugwarrior/services/__init__.py, bugwarrior/services/github.py
One from #302 and another from #303.
=> Fix bugs from some recent PRs.

bugwarrior/README.rst, bugwarrior/docs/services/gerrit.rst, bugwarrior/services/gerrit.py, setup.py, tests/test_gerrit.py
It works!
I noticed while doing this that the IssueService.validate_config call is still
non-idiomatic, fwiw.
=> A gerrit service.

.travis.yml, bugwarrior/services/activecollab2.py, bugwarrior/services/taiga.py, setup.py, tests/base.py, tests/test_activecollab.py, tests/test_activecollab2.py, tests/test_bitbucket.py, tests/test_bugzilla.py, tests/test_gerrit.py, tests/test_github.py, tests/test_gitlab.py, tests/test_jira.py, tests/test_megaplan.py, tests/test_redmine.py, tests/test_taiga.py, tests/test_teamlab.py, tests/test_templates.py, tests/test_trac.py
- Significantly increases test coverage.
- Includes some bugfixes for bugs uncovered by the tests.
- Caught both regressions fixed by #306 during development, though @ralphbean beat me to fixing them.
=> Test IssueService.issues()

bugwarrior/db.py, bugwarrior/services/__init__.py, bugwarrior/services/bitbucket.py, tests/test_bitbucket.py
This fixes a couple of issues I noticed with the bitbucket service in the latest version:
* bugwarrior was only pulling a small number of issues from bitbucket
* when using `only_if_assigned`, no issues were imported
=> Bitbucket fixes

.github/CONTRIBUTING.md, bugwarrior/docs/contributing.rst
Seem commit messages for detail.
=> More contributing docs

bugwarrior/services/bitbucket.py
Just a few things I noticed while reviewing @gdetrez's PR. See commit messages for detail.
=> Minor Bitbucket refactorings

bugwarrior/services/jira.py, tests/test_jira.py
Include Fix Version
Prevent Jira from logging user out of web client
Get ticket creation time.
=> Improve JIRA integration

bugwarrior/config.py
=> Fix messed up logging in die().

bugwarrior/services/trac.py
=> Store Trac component in UDA for Trac service

bugwarrior/docs/services/trac.rst
Forgot to document this in the previous pull request.
=> Update Sphinx docs to reflect new traccomponent UDA

bugwarrior/docs/common_configuration.rst
Re-structure the text and add an example on how to use bugwarrior with
pass.
=> Improve @oracle documentation

bugwarrior/docs/common_configuration.rst
This is just documenting an existing option, not adding a new one.
=> Add documentation for static_fields config

bugwarrior/docs/contributing.rst, bugwarrior/docs/getting.rst
An other documentation fix: add a requirement section as suggested in #404.
=> Add requirements to documentation

bugwarrior/docs/faq.rst, bugwarrior/docs/index.rst
There are regularly new requests to support other ITS (#87, #204, #311, #356, #388, #400, #409...) so I tried to compile old answer to such issues and put the result in a new FAQ in the docs.
=> Add an FAQ

bugwarrior/db.py, tests/test_db.py
<s>Based on #364 and #382, so not really a reasonable thing to review right now but I thought I'd throw it up here to avoid duplication of effort and showcase codecov. I may add more tests in the meantime.</s> Rebased and should be good to go.
=> Test db module

bugwarrior/services/taiga.py
=> Check for errors from the taiga API and surface them.

bugwarrior/README.rst, bugwarrior/docs/services/gitlab.rst, bugwarrior/docs/services/jira.rst, bugwarrior/docs/services/youtrack.rst, bugwarrior/services/youtrack.py, setup.py, tests/test_youtrak.py
* Implementation of Feature Proposal #356 (Support for youtrack).
* Additional features include tag importing and query customization.
* PR includes new service, appropriate tests, and documentation.
=> Add support for YouTrack issue tracker.

bugwarrior/services/jira.py
=> We should verify by default here.

bugwarrior/services/jira.py
Not sure why this we didn't include these to begin with.
=> Include the issue url for jira tasks even if there are no annotations.

.travis.yml, bugwarrior/docs/services/github.rst, bugwarrior/services/github.py, tests/test_github.py
Add support for GitHub Enterprize by adding a `github.host` configuration option (issue #360)
=> #360: Enterprize GitHub support

bugwarrior/services/trac.py
=> Interpret trac.no_xmlrpc as a bool.

bugwarrior/services/github.py
=> Warn about the misleading 404 error code from github.

bugwarrior/db.py, tests/test_db.py
=> Decode all byte strings from utf8 before any db actions.

bugwarrior/services/gerrit.py, tests/base.py, tests/test_gerrit.py
Fixed #463 unable to login to gerrithub.io
Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>
=> Added authentication method detection to gerrit

bugwarrior/services/github.py
=> github: fix mentions filter, add option to prefix project name with org name

tests/test_bitbucket.py, tests/test_gerrit.py
=> Update tests to support responses-0.6.

bugwarrior/services/bitbucket.py, bugwarrior/services/gitlab.py
I implemented #484  for Gitlab and Bitbucket.
=> Prefix project name with git service namespace

bugwarrior/services/bz.py
=> Work around bugzilla flags issue

bugwarrior/services/__init__.py
Noticed this while working on another PR.
=> Remove unnecessary conditional

bugwarrior/services/github.py, bugwarrior/services/gitlab.py, tests/test_github.py, tests/test_gitlab.py
- GitHub service
- GitLab service
---
- tested locally
- see #578
=> uses created at service date as entry date

bugwarrior/services/taiga.py, tests/test_taiga.py
This is an attempt to fix #591 as taiga returns a list of arrays using multiple tags.
=> build list for multiple taiga tags

tests/test_gitlab.py
=> gitlab: fixes tests

bugwarrior/docs/services/phabricator.rst, bugwarrior/services/phab.py
=> Allow disabling specific Phabricator components

setup.py
=> Unpin futures to avoid dependency conflicts

.travis.yml, tox.ini
Just moving the python3 versions here.  No need to test against
those older py3 versions anymore.
=> Update python3 versions.

bugwarrior/services/gitlab.py
This PR updates the work done in #495 with develop, solving all conflicts.
The author (@pjf) discussed the possibility of using yield inside the new method instead of returning a list, so I did it this way.
=> Reduce redundant code in services/gitlab.py

bugwarrior/services/jira.py
This is nice for people like me living out of kanban.  :)
=> Use explicit due date from jira, if set.
